package by.allahverdiev.finaltask.controller.command;

public enum CommandName {
    FIND_PRODUCT_BY_ID,
    FIND_PRODUCT_BY_NAME,
    FIND_ALL_PRODUCTS_IN_CURRENT_DATE,
    FIND_ARRIVALS_IN_CURRENT_DATE,
    FIND_ALL_NEED,
    FIND_NEED_FOR_MONTH,
    ADD_ARCHIVE_ENTRY,
    ADD_ARRIVAL_ENTRY,
    FIND_ARCHIVE_ENTRY_BY_MONTH,
    FIND_ALL_ARCHIVE,
    LOGIN,
    LOGOUT,
    SEARCH,
    FIND_DEFICIT,
    REFRESH,
    CHANGE_LANGUAGE
}
